
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="ko">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>5. 내장 예외 &#8212; Python 3.6.5 documentation</title>
    <link rel="stylesheet" href="../_static/pydoctheme.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '3.6.5',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true,
        SOURCELINK_SUFFIX: '.txt'
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/translations.js"></script>
    <script type="text/javascript" src="../_static/sidebar.js"></script>
    <link rel="search" type="application/opensearchdescription+xml"
          title="Python 3.6.5 documentation에서 찾기"
          href="../_static/opensearch.xml"/>
    <link rel="author" title="이 문서 정보" href="../about.html" />
    <link rel="index" title="색인" href="../genindex.html" />
    <link rel="search" title="검색" href="../search.html" />
    <link rel="copyright" title="저작권" href="../copyright.html" />
    <link rel="next" title="6. Text Processing Services" href="text.html" />
    <link rel="prev" title="4. 내장형" href="stdtypes.html" />
    <link rel="shortcut icon" type="image/png" href="../_static/py.png" />
    <link rel="canonical" href="http://python.flowdas.com/library/exceptions.html" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112027364-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-112027364-1');
    </script>
    
    <script type="text/javascript" src="../_static/copybutton.js"></script>
    <script type="text/javascript" src="../_static/switchers.js"></script>
    
    
 

  </head>
  <body>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>탐색</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="일반 색인"
             accesskey="I">색인</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python 모듈 목록"
             >모듈</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. Text Processing Services"
             accesskey="N">다음</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. 내장형"
             accesskey="P">이전</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &#187;</li>
        <li>
          <a href="../index.html">도큐멘테이션 </a> &#187;
        </li>

          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">파이썬 표준 라이브러리</a> &#187;</li>
    <li class="right">
        

    <div class="inline-search" style="display: none" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="빠른 검색" type="text" name="q" />
          <input type="submit" value="Go" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
    <script type="text/javascript">$('.inline-search').show(0);</script>
         |
    </li>

      </ul>
    </div>    

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="built-in-exceptions">
<span id="bltin-exceptions"></span><h1>5. 내장 예외<a class="headerlink" href="#built-in-exceptions" title="제목 주소">¶</a></h1>
<p id="index-0">파이썬에서, 모든 예외는 <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-class docutils literal"><span class="pre">BaseException</span></code></a> 에서 파생 된 클래스의 인스턴스 여야합니다. 특정 클래스를 언급하는 <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal"><span class="pre">except</span></code></a> 절을 갖는 <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal"><span class="pre">try</span></code></a> 문에서, 그 절은 그 클래스에서 파생 된 모든 예외 클래스를 처리합니다 (하지만 <em>그 것</em>이 계승하는 예외 클래스는 처리하지 않습니다). 서브 클래싱을 통해 관련되지 않은 두 개의 예외 클래스는 같은 이름을 갖는다 할지라도 결코 등등하게 취급되지 않습니다.</p>
<p id="index-1">아래 나열된 내장 예외는 인터프리터나 내장 함수에 의해 생성 될 수 있습니다. 따로 언급 된 경우를 제외하고는, 에러의 자세한 원인을 나타내는 &quot;연관된 값&quot; 을 갖습니다. 이것은 여러 항목의 정보 (예, 에러 코드와 그 코드를 설명하는 문자열)를 담은 문자열이나 튜플 일 수 있습니다. 연관된 값은 보통 예외 클래스의 생성자에 인자로 전달됩니다.</p>
<p>사용자 코드는 내장 예외를 일으킬 수 있습니다. 이것은 예외 처리기를 검사하거나 인터프리터가 같은 예외를 발생시키는 상황과 &quot;같은&quot; 에러 조건을 보고하는 데 사용할 수 있습니다. 그러나 사용자 코드가 부적절한 에러를 발생시키는 것을 막을 수 있는 방법이 없음을 유의하십시오.</p>
<p>내장 예외 클래스는 새 예외를 정의하기 위해 서브 클래싱 될 수 있습니다. <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> 이 아니라 <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> 클래스 나 그 서브 클래스 중 하나에서 새로운 예외를 파생시킬 것을 권장합니다. 예외 정의에 대한 더 많은 정보는 파이썬 자습서의 <a class="reference internal" href="../tutorial/errors.html#tut-userexceptions"><span class="std std-ref">사용자 정의 예외</span></a> 에 있습니다.</p>
<p><a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal"><span class="pre">except</span></code></a> 또는 <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal"><span class="pre">finally</span></code></a> 절에서 예외를 일으킬 때 (또는 다시 일으킬 때), <code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> 는 자동으로 마지막으로 잡힌 예외로 설정됩니다; 이 새 예외가 처리되지 않으면, 결국 표시되는 트레이스백은 원래 예외와 최종 예외를 포함합니다.</p>
<p>(현재 처리중인 예외를 다시 발생시키기 위해 <code class="docutils literal"><span class="pre">raise</span></code> 만 사용하는 대신) 새 예외를 일으킬 때, 묵시적인 예외 컨텍스트는 암시적인 예외 상황은 명시적 원인으로 보충 될 수 있는데, <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal"><span class="pre">raise</span></code></a> 와 <a class="reference internal" href="../reference/simple_stmts.html#from"><code class="xref std std-keyword docutils literal"><span class="pre">from</span></code></a> 을 사용합니다:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">new_exc</span> <span class="kn">from</span> <span class="nn">original_exc</span>
</pre></div>
</div>
<p><a class="reference internal" href="../reference/simple_stmts.html#from"><code class="xref std std-keyword docutils literal"><span class="pre">from</span></code></a> 다음의 표현식은 예외이거나 <code class="docutils literal"><span class="pre">None</span></code> 이어야합니다. 이 표현식을 새로 일으키는 예외의 <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> 로 설정합니다. <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> 를 설정하면, 묵시적으로 <code class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></code> 를 <code class="docutils literal"><span class="pre">True</span></code> 로 설정합니다. 그래서, <code class="docutils literal"><span class="pre">raise</span> <span class="pre">new_exc</span> <span class="pre">from</span> <span class="pre">None</span></code> 을 사용하면 표시의 목적상 이전 예외를 새로운 것으로 대체 하는 효과를 주면서 (예를 들어 <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal"><span class="pre">KeyError</span></code></a> 를 <a class="reference internal" href="#AttributeError" title="AttributeError"><code class="xref py py-exc docutils literal"><span class="pre">AttributeError</span></code></a> 로), 디버깅할 때  검사할 수 있도록 이전의 예외를 <code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> 에 남겨둡니다.</p>
<p>기본 트레이스백 표시 코드는 예외 자체의 트레이스백뿐만 아니라 이러한 연결된 예외를 보여줍니다. <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> 에 명시적으로 연결된 예외는 있으면 항상 표시됩니다. <code class="xref py py-attr docutils literal"><span class="pre">__context__</span></code> 에 묵시적으로 연결된 예외는 <code class="xref py py-attr docutils literal"><span class="pre">__cause__</span></code> 가 <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> 이고 <code class="xref py py-attr docutils literal"><span class="pre">__suppress_context__</span></code> 가 거짓인 경우에만 표시됩니다.</p>
<p>두 경우 모두, 예외 자신은 항상 연결된 예외 뒤에 표시되어서, 트레이스백의 마지막 줄은 항상 마지막에 발생한 예외를 보여줍니다.</p>
<div class="section" id="base-classes">
<h2>5.1. 베이스 클래스<a class="headerlink" href="#base-classes" title="제목 주소">¶</a></h2>
<p>다음 예외는 주로 다른 예외의 베이스 클래스로 사용됩니다.</p>
<dl class="exception">
<dt id="BaseException">
<em class="property">exception </em><code class="descname">BaseException</code><a class="headerlink" href="#BaseException" title="정의 주소">¶</a></dt>
<dd><p>모든 내장 예외의 베이스 클래스입니다. 사용자 정의 클래스에 의해 직접적으로 상속되는 것이 아닙니다 (그런 목적으로는 <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> 을 사용하세요). 이 클래스의 인스턴스에 대해 <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a> 이 호출되면, 인스턴스로 전달된 인자(들)의 표현을 돌려줍니다. 인자가 없는 경우는 빈 문자열을 돌려줍니다.</p>
<dl class="attribute">
<dt id="BaseException.args">
<code class="descname">args</code><a class="headerlink" href="#BaseException.args" title="정의 주소">¶</a></dt>
<dd><p>예외 생성자에 주어진 인자들의 튜플. 일부 내장 예외(예, <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>)는 특정 수의 인자를 기대하고 이 튜플의 요소에 특별한 의미를 할당하는 반면, 다른 것들은 보통 오류 메시지를 제공하는 단일 문자열로만 호출됩니다.</p>
</dd></dl>

<dl class="method">
<dt id="BaseException.with_traceback">
<code class="descname">with_traceback</code><span class="sig-paren">(</span><em>tb</em><span class="sig-paren">)</span><a class="headerlink" href="#BaseException.with_traceback" title="정의 주소">¶</a></dt>
<dd><p>이 메서드는 <em>tb</em> 를 예외의 새 트레이스백으로 설정하고 예외 객체를 돌려줍니다. 일반적으로 다음과 같은 예외 처리 코드에서 사용됩니다:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
    <span class="n">tb</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">2</span><span class="p">]</span>
    <span class="k">raise</span> <span class="n">OtherException</span><span class="p">(</span><span class="o">...</span><span class="p">)</span><span class="o">.</span><span class="n">with_traceback</span><span class="p">(</span><span class="n">tb</span><span class="p">)</span>
</pre></div>
</div>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="Exception">
<em class="property">exception </em><code class="descname">Exception</code><a class="headerlink" href="#Exception" title="정의 주소">¶</a></dt>
<dd><p>모든 시스템 종료 외의 내장 예외는 이 클래스 파생됩니다. 모든 사용자 정의 예외도 이 클래스에서 파생되어야합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="ArithmeticError">
<em class="property">exception </em><code class="descname">ArithmeticError</code><a class="headerlink" href="#ArithmeticError" title="정의 주소">¶</a></dt>
<dd><p>다양한 산술 에러가 일으키는 내장 예외들의 베이스 클래스: <a class="reference internal" href="#OverflowError" title="OverflowError"><code class="xref py py-exc docutils literal"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="#FloatingPointError" title="FloatingPointError"><code class="xref py py-exc docutils literal"><span class="pre">FloatingPointError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="BufferError">
<em class="property">exception </em><code class="descname">BufferError</code><a class="headerlink" href="#BufferError" title="정의 주소">¶</a></dt>
<dd><p><a class="reference internal" href="../c-api/buffer.html#bufferobjects"><span class="std std-ref">버퍼</span></a> 관련 연산을 수행할 수 없을 때 발생합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="LookupError">
<em class="property">exception </em><code class="descname">LookupError</code><a class="headerlink" href="#LookupError" title="정의 주소">¶</a></dt>
<dd><p>매핑 또는 시퀀스에 사용 된 키 나 인덱스가 잘못되었을 때 발생하는 예외의 베이스 클래스: <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a>, <a class="reference internal" href="#KeyError" title="KeyError"><code class="xref py py-exc docutils literal"><span class="pre">KeyError</span></code></a>. <a class="reference internal" href="codecs.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal"><span class="pre">codecs.lookup()</span></code></a> 은 이 예외를 직접 일으킬 수 있습니다.</p>
</dd></dl>

</div>
<div class="section" id="concrete-exceptions">
<h2>5.2. 구체적인 예외<a class="headerlink" href="#concrete-exceptions" title="제목 주소">¶</a></h2>
<p>다음 예외는 일반적으로 직접 일으키는데 사용하는 예외입니다.</p>
<dl class="exception">
<dt id="AssertionError">
<em class="property">exception </em><code class="descname">AssertionError</code><a class="headerlink" href="#AssertionError" title="정의 주소">¶</a></dt>
<dd><p id="index-2"><a class="reference internal" href="../reference/simple_stmts.html#assert"><code class="xref std std-keyword docutils literal"><span class="pre">assert</span></code></a> 문이 실패 할 때 발생합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="AttributeError">
<em class="property">exception </em><code class="descname">AttributeError</code><a class="headerlink" href="#AttributeError" title="정의 주소">¶</a></dt>
<dd><p>어트리뷰트 참조(<a class="reference internal" href="../reference/expressions.html#attribute-references"><span class="std std-ref">어트리뷰트 참조</span></a> 를 보세요)나 대입이 실패할 때 발생합니다. (객체가 어트리뷰트 참조나 어트리뷰트 대입을 아예 지원하지 않으면 <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> 가 발생합니다.)</p>
</dd></dl>

<dl class="exception">
<dt id="EOFError">
<em class="property">exception </em><code class="descname">EOFError</code><a class="headerlink" href="#EOFError" title="정의 주소">¶</a></dt>
<dd><p><a class="reference internal" href="functions.html#input" title="input"><code class="xref py py-func docutils literal"><span class="pre">input()</span></code></a> 함수가 데이터를 읽지 못한 상태에서 EOF (end-of-file) 조건을 만날 때 발생합니다. (주의하세요: <code class="xref py py-meth docutils literal"><span class="pre">io.IOBase.read()</span></code> 와 <a class="reference internal" href="io.html#io.IOBase.readline" title="io.IOBase.readline"><code class="xref py py-meth docutils literal"><span class="pre">io.IOBase.readline()</span></code></a> 메서드는 EOF를 만날 때 빈 문자열을 돌려줍니다.)</p>
</dd></dl>

<dl class="exception">
<dt id="FloatingPointError">
<em class="property">exception </em><code class="descname">FloatingPointError</code><a class="headerlink" href="#FloatingPointError" title="정의 주소">¶</a></dt>
<dd><p>부동 소수점 연산이 실패 할 때 발생합니다. 이 예외는 항상 정의되어 있지만, 파이썬이 <code class="docutils literal"><span class="pre">--with-fpectl</span></code> 옵션으로 설정되었거나, <code class="xref py py-const docutils literal"><span class="pre">WANT_SIGFPE_HANDLER</span></code> 심볼이 <code class="file docutils literal"><span class="pre">pyconfig.h</span></code> 파일에 정의되어있을  때만 발생합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="GeneratorExit">
<em class="property">exception </em><code class="descname">GeneratorExit</code><a class="headerlink" href="#GeneratorExit" title="정의 주소">¶</a></dt>
<dd><p><a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">제너레이터</span></a> 또는 <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">코루틴</span></a> 이 닫힐 때 발생합니다; <a class="reference internal" href="../reference/expressions.html#generator.close" title="generator.close"><code class="xref py py-meth docutils literal"><span class="pre">generator.close()</span></code></a> 와 <a class="reference internal" href="../reference/datamodel.html#coroutine.close" title="coroutine.close"><code class="xref py py-meth docutils literal"><span class="pre">coroutine.close()</span></code></a> 를 보십시오. 기술적으로 에러가 아니기 때문에 <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> 대신에 <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> 을 직접 계승합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="ImportError">
<em class="property">exception </em><code class="descname">ImportError</code><a class="headerlink" href="#ImportError" title="정의 주소">¶</a></dt>
<dd><p><a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a> 문이 모듈을 로드하는 데 문제가 있을 때 발생합니다. 또한 <code class="docutils literal"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code> 에서 임포트하려는 이름을 찾을 수 없을 때도 발생합니다.</p>
<p><code class="xref py py-attr docutils literal"><span class="pre">name</span></code> 과 <code class="xref py py-attr docutils literal"><span class="pre">path</span></code> 어트리뷰트는 생성자에 키워드 전용 인자를 사용하여 설정할 수 있습니다. 설정된 경우, 각각 임포트하려고 시도한 모듈의 이름과 예외를 유발한 파일의 경로를 나타냅니다.</p>
<div class="versionchanged">
<p><span class="versionmodified">버전 3.3으로 변경: </span><code class="xref py py-attr docutils literal"><span class="pre">name</span></code> 과 <code class="xref py py-attr docutils literal"><span class="pre">path</span></code> 어트리뷰트를 추가했습니다.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="ModuleNotFoundError">
<em class="property">exception </em><code class="descname">ModuleNotFoundError</code><a class="headerlink" href="#ModuleNotFoundError" title="정의 주소">¶</a></dt>
<dd><p><a class="reference internal" href="#ImportError" title="ImportError"><code class="xref py py-exc docutils literal"><span class="pre">ImportError</span></code></a> 의 서브 클래스인데, 모듈을 찾을 수 없을 때 <a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a> 가 일으킵니다. <a class="reference internal" href="sys.html#sys.modules" title="sys.modules"><code class="xref py py-data docutils literal"><span class="pre">sys.modules</span></code></a> 에서 <code class="docutils literal"><span class="pre">None</span></code> 이 발견될 때도 발생합니다.</p>
<div class="versionadded">
<p><span class="versionmodified">버전 3.6에 추가.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="IndexError">
<em class="property">exception </em><code class="descname">IndexError</code><a class="headerlink" href="#IndexError" title="정의 주소">¶</a></dt>
<dd><p>시퀀스 인덱스가 범위를 벗어날 때 발생합니다. (슬라이스 인덱스는 허용 된 범위 내에 들어가도록 자동으로 잘립니다; 인덱스가 정수가 아니면 <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> 가 발생합니다.)</p>
</dd></dl>

<dl class="exception">
<dt id="KeyError">
<em class="property">exception </em><code class="descname">KeyError</code><a class="headerlink" href="#KeyError" title="정의 주소">¶</a></dt>
<dd><p>매핑 (딕셔너리) 키가 기존 키 집합에서 발견되지 않을 때 발생합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="KeyboardInterrupt">
<em class="property">exception </em><code class="descname">KeyboardInterrupt</code><a class="headerlink" href="#KeyboardInterrupt" title="정의 주소">¶</a></dt>
<dd><p>사용자가 인터럽트 키(일반적으로 <code class="kbd docutils literal"><span class="pre">Control-C</span></code> 또는 <code class="kbd docutils literal"><span class="pre">Delete</span></code>)를 누를 때 발생합니다. 실행 중에 인터럽트 검사가 정기적으로 수행됩니다. <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> 을 잡는 코드에 의해 우연히 잡혀서, 인터프리터가 종료하는 것을 막지 못하도록 <a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> 를 계승합니다.</p>
</dd></dl>

<dl class="exception">
<dt id="MemoryError">
<em class="property">exception </em><code class="descname">MemoryError</code><a class="headerlink" href="#MemoryError" title="정의 주소">¶</a></dt>
<dd><p>작업에 메모리가 부족하지만 상황이 여전히 (일부 객체를 삭제해서) 복구 될 수 있는 경우 발생합니다. 연관된 값은 어떤 종류의 (내부) 연산이 메모리를 다 써 버렸는지를 나타내는 문자열입니다. 하부 메모리 관리 아키텍처(C의 <code class="xref c c-func docutils literal"><span class="pre">malloc()</span></code> 함수)때문에, 인터프리터가 항상 이 상황을 완벽하게 복구 할 수 있는 것은 아닙니다; 그럼에도 불구하고 통제를 벗어난 프로그램이 원인인 경우 스택 트레이스백을 인쇄 할 수 있도록 예외를 일으킵니다.</p>
</dd></dl>

<dl class="exception">
<dt id="NameError">
<em class="property">exception </em><code class="descname">NameError</code><a class="headerlink" href="#NameError" title="정의 주소">¶</a></dt>
<dd><p>지역 또는 전역 이름을 찾을 수 없을 때 발생합니다. 이는 정규화되지 않은 이름에만 적용됩니다. 연관된 값은 찾을 수 없는 이름을 포함하는 에러 메시지입니다.</p>
</dd></dl>

<dl class="exception">
<dt id="NotImplementedError">
<em class="property">exception </em><code class="descname">NotImplementedError</code><a class="headerlink" href="#NotImplementedError" title="정의 주소">¶</a></dt>
<dd><p>이 예외는 <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> 에서 파생됩니다. 사용자 정의 베이스 클래스에서, 파생 클래스가 재정의하도록 요구하는 추상 메서드나, 클래스가 개발되는 도중에 실제 구현이 추가될 필요가 있음을 나타낼 때 이 예외를 발생시켜야 합니다.</p>
<div class="admonition note">
<p class="first admonition-title">주석</p>
<p class="last">연산자 나 메서드가 아예 지원되지 않는다는 것을 나타내는 데 사용해서는 안됩니다 -- 그 경우는 연산자 / 메소드를 정의하지 않거나, 서브 클래스인 경우 <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-data docutils literal"><span class="pre">None</span></code></a> 으로 설정하십시오.</p>
</div>
<div class="admonition note">
<p class="first admonition-title">주석</p>
<p class="last"><code class="docutils literal"><span class="pre">NotImplementedError</span></code> 와 <code class="docutils literal"><span class="pre">NotImplemented</span></code> 는 비슷한 이름과 목적을 가지고 있습니다만, 바꿔쓸 수 없습니다. 언제 사용하는지에 대한 자세한 내용은 <a class="reference internal" href="constants.html#NotImplemented" title="NotImplemented"><code class="xref py py-data docutils literal"><span class="pre">NotImplemented</span></code></a> 를 찹조하세요.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="OSError">
<em class="property">exception </em><code class="descname">OSError</code><span class="sig-paren">(</span><span class="optional">[</span><em>arg</em><span class="optional">]</span><span class="sig-paren">)</span><a class="headerlink" href="#OSError" title="정의 주소">¶</a></dt>
<dt>
<em class="property">exception </em><code class="descname">OSError</code><span class="sig-paren">(</span><em>errno</em>, <em>strerror</em><span class="optional">[</span>, <em>filename</em><span class="optional">[</span>, <em>winerror</em><span class="optional">[</span>, <em>filename2</em><span class="optional">]</span><span class="optional">]</span><span class="optional">]</span><span class="sig-paren">)</span></dt>
<dd><p id="index-3">이 예외는 시스템 함수가 시스템 관련 에러를 돌려줄 때 발생하는데, &quot;파일을 찾을 수 없습니다(file not found)&quot; 나 &quot;디스크가 꽉 찼습니다(disk full)&quot; 와 같은 (잘못된 인자 형이나 다른 부수적인 에러가 아닌) 입출력 실패를 포함합니다.</p>
<p>생성자의 두 번째 형식은 아래에 설명 된 해당 어트리뷰트를 설정합니다. 어트리뷰트를 지정하지 않으면 기본적으로 <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> 이 됩니다. 이전 버전과의 호환성을 위해, 세 개의 인자가 전달되면, <a class="reference internal" href="#BaseException.args" title="BaseException.args"><code class="xref py py-attr docutils literal"><span class="pre">args</span></code></a> 어트리뷰트는 처음 두 생성자 인자의 2-튜플 만 포함합니다.</p>
<p>아래의 <a class="reference internal" href="#os-exceptions">OS exceptions</a> 에서 설명하는 것처럼, 생성자는 종종 <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> 의 서브 클래스를 돌려줍니다. 구체적인 서브 클래스는 최종 <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 값에 따라 다릅니다. 이 동작은 <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> 를 직접 혹은 별칭을 통해 생성할 때만 일어나고, 서브클래싱할 때는 상속되지 않습니다.</p>
<dl class="attribute">
<dt id="OSError.errno">
<code class="descname">errno</code><a class="headerlink" href="#OSError.errno" title="정의 주소">¶</a></dt>
<dd><p>C 변수 <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> 로부터 온 숫자 에러 코드.</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.winerror">
<code class="descname">winerror</code><a class="headerlink" href="#OSError.winerror" title="정의 주소">¶</a></dt>
<dd><p>윈도우에서, 네이티브 윈도우 에러 코드를 제공합니다. <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 어트리뷰트는 이 네이티브 에러 코드를 POSIX 코드로 대략적으로 변환한 것입니다.</p>
<p>윈도우에서, <em>winerror</em> 생성자 인자가 정수인 경우, <a class="reference internal" href="#OSError.errno" title="OSError.errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> 어트리뷰트는 윈도우 에러 코드에서 결정되며 <em>errno</em> 인자는 무시됩니다. 다른 플랫폼에서는 <em>winerror</em> 인자가 무시되고 <a class="reference internal" href="#OSError.winerror" title="OSError.winerror"><code class="xref py py-attr docutils literal"><span class="pre">winerror</span></code></a> 어트리뷰트가 없습니다.</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.strerror">
<code class="descname">strerror</code><a class="headerlink" href="#OSError.strerror" title="정의 주소">¶</a></dt>
<dd><p>운영 체제에서 제공하는 해당 에러 메시지. POSIX에서는 C 함수 <code class="xref c c-func docutils literal"><span class="pre">perror()</span></code> 로, 윈도우에서는 <code class="xref c c-func docutils literal"><span class="pre">FormatMessage()</span></code> 로 포맷합니다.</p>
</dd></dl>

<dl class="attribute">
<dt id="OSError.filename">
<code class="descname">filename</code><a class="headerlink" href="#OSError.filename" title="정의 주소">¶</a></dt>
<dt id="OSError.filename2">
<code class="descname">filename2</code><a class="headerlink" href="#OSError.filename2" title="정의 주소">¶</a></dt>
<dd><p>(<a class="reference internal" href="functions.html#open" title="open"><code class="xref py py-func docutils literal"><span class="pre">open()</span></code></a> 또는 <a class="reference internal" href="os.html#os.unlink" title="os.unlink"><code class="xref py py-func docutils literal"><span class="pre">os.unlink()</span></code></a> 와 같은) 파일 시스템 경로와 관련된 예외의 경우, <a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal"><span class="pre">filename</span></code></a> 은 함수에 전달 된 파일 이름입니다. (<a class="reference internal" href="os.html#os.rename" title="os.rename"><code class="xref py py-func docutils literal"><span class="pre">os.rename()</span></code></a> 처럼) 두개의 파일 시스템 경로를 수반하는 함수의 경우, <a class="reference internal" href="#OSError.filename2" title="OSError.filename2"><code class="xref py py-attr docutils literal"><span class="pre">filename2</span></code></a> 는 두 번째 파일 이름에 해당합니다.</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified">버전 3.3으로 변경: </span><a class="reference internal" href="#EnvironmentError" title="EnvironmentError"><code class="xref py py-exc docutils literal"><span class="pre">EnvironmentError</span></code></a>, <a class="reference internal" href="#IOError" title="IOError"><code class="xref py py-exc docutils literal"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="#WindowsError" title="WindowsError"><code class="xref py py-exc docutils literal"><span class="pre">WindowsError</span></code></a>, <a class="reference internal" href="socket.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal"><span class="pre">socket.error</span></code></a>, <a class="reference internal" href="select.html#select.error" title="select.error"><code class="xref py py-exc docutils literal"><span class="pre">select.error</span></code></a>, <code class="xref py py-exc docutils literal"><span class="pre">mmap.error</span></code> 가 <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> 로 병합되었고, 생성자는 서브 클래스를 반환 할 수 있습니다.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">버전 3.4으로 변경: </span><a class="reference internal" href="#OSError.filename" title="OSError.filename"><code class="xref py py-attr docutils literal"><span class="pre">filename</span></code></a> 속성은 이제 파일 시스템 인코딩으로 인코딩되거나 디코딩 된 이름 대신 함수에 전달 된 원래 파일 이름입니다. 또한 <em>filename2</em> 생성자 인자 및 어트리뷰트가 추가되었습니다.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="OverflowError">
<em class="property">exception </em><code class="descname">OverflowError</code><a class="headerlink" href="#OverflowError" title="정의 주소">¶</a></dt>
<dd><p>산술 연산의 결과가 너무 커서 표현할 수 없을 때 발생합니다. 정수에서는 발생하지 않습니다 (포기하기 보다는 <a class="reference internal" href="#MemoryError" title="MemoryError"><code class="xref py py-exc docutils literal"><span class="pre">MemoryError</span></code></a> 를 일으키게될 겁니다). 그러나, 역사적인 이유로, 때로 OverflowError는 요구되는 범위를 벗어난 정수의 경우도 발생합니다. C에서 부동 소수점 예외 처리의 표준화가 부족하기 때문에, 대부분의 부동 소수점 연산은 검사되지 않습니다.</p>
</dd></dl>

<dl class="exception">
<dt id="RecursionError">
<em class="property">exception </em><code class="descname">RecursionError</code><a class="headerlink" href="#RecursionError" title="정의 주소">¶</a></dt>
<dd><p>이 예외는 <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> 에서 파생됩니다. 인터프리터가 최대 재귀 깊이(<a class="reference internal" href="sys.html#sys.getrecursionlimit" title="sys.getrecursionlimit"><code class="xref py py-func docutils literal"><span class="pre">sys.getrecursionlimit()</span></code></a> 참조)가 초과되었음을 감지할 때 발생합니다.</p>
<div class="versionadded">
<p><span class="versionmodified">버전 3.5에 추가: </span>이전에는 평범한 <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> 가 발생했습니다.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="ReferenceError">
<em class="property">exception </em><code class="descname">ReferenceError</code><a class="headerlink" href="#ReferenceError" title="정의 주소">¶</a></dt>
<dd><p>이 예외는 <a class="reference internal" href="weakref.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal"><span class="pre">weakref.proxy()</span></code></a> 함수가 만든 약한 참조 프록시가 이미 가비지 수집 된 참조 대상의 어트리뷰트를 액세스하는 데 사용될 때 발생합니다. 약한 참조에 대한 더 자세한 정보는 <a class="reference internal" href="weakref.html#module-weakref" title="weakref: Support for weak references and weak dictionaries."><code class="xref py py-mod docutils literal"><span class="pre">weakref</span></code></a> 모듈을 보십시오.</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeError">
<em class="property">exception </em><code class="descname">RuntimeError</code><a class="headerlink" href="#RuntimeError" title="정의 주소">¶</a></dt>
<dd><p>다른 범주에 속하지 않는 에러가 감지될 때 발생합니다. 연관된 값은 정확히 무엇이 잘못되었는지를 나타내는 문자열입니다.</p>
</dd></dl>

<dl class="exception">
<dt id="StopIteration">
<em class="property">exception </em><code class="descname">StopIteration</code><a class="headerlink" href="#StopIteration" title="정의 주소">¶</a></dt>
<dd><p>이터레이터에 의해 생성 된 항목이 더 이상 없다는 것을 알려주기위해, 내장 함수 <a class="reference internal" href="functions.html#next" title="next"><code class="xref py py-func docutils literal"><span class="pre">next()</span></code></a> 와 <a class="reference internal" href="../glossary.html#term-iterator"><span class="xref std std-term">이터레이터</span></a>의 <a class="reference internal" href="stdtypes.html#iterator.__next__" title="iterator.__next__"><code class="xref py py-meth docutils literal"><span class="pre">__next__()</span></code></a> 메서드가 일으킵니다.</p>
<p>예외 객체는 <code class="xref py py-attr docutils literal"><span class="pre">value</span></code> 라는 하나의 어트리뷰트를 가지고 있습니다. 이 어트리뷰트는 예외를 생성 할 때 인자로 주어지며, 기본값은 <a class="reference internal" href="constants.html#None" title="None"><code class="xref py py-const docutils literal"><span class="pre">None</span></code></a> 입니다.</p>
<p><a class="reference internal" href="../glossary.html#term-generator"><span class="xref std std-term">제너레이터</span></a> 나 <a class="reference internal" href="../glossary.html#term-coroutine"><span class="xref std std-term">코루틴</span></a> 함수가 복귀할 때, 새 <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> 인스턴스를 발생시키고, 함수가 돌려주는 값을 예외 생성자의 <code class="xref py py-attr docutils literal"><span class="pre">value</span></code> 파라미터로 사용합니다.</p>
<p><code class="docutils literal"><span class="pre">from</span> <span class="pre">__future__</span> <span class="pre">import</span> <span class="pre">generator_stop</span></code> 지시어가 있는 상태에서 정의 된 제너레이터 함수가 <a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> 를 일으키면, <a class="reference internal" href="#RuntimeError" title="RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a> 로 변환됩니다 (<a class="reference internal" href="#StopIteration" title="StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a> 은 새 예외의 원인(<code class="docutils literal"><span class="pre">__cause__</span></code>)으로 남겨둡니다).</p>
<div class="versionchanged">
<p><span class="versionmodified">버전 3.3으로 변경: </span><code class="docutils literal"><span class="pre">value</span></code> 어트리뷰트와 제너레이터 함수가 이 값을 돌려주는 기능을 추가했습니다.</p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">버전 3.5으로 변경: </span>RuntimeError 변환을 도입했습니다.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="StopAsyncIteration">
<em class="property">exception </em><code class="descname">StopAsyncIteration</code><a class="headerlink" href="#StopAsyncIteration" title="정의 주소">¶</a></dt>
<dd><p>Must be raised by <a class="reference internal" href="../reference/datamodel.html#object.__anext__" title="object.__anext__"><code class="xref py py-meth docutils literal"><span class="pre">__anext__()</span></code></a> method of an
<a class="reference internal" href="../glossary.html#term-asynchronous-iterator"><span class="xref std std-term">asynchronous iterator</span></a> object to stop the iteration.</p>
<div class="versionadded">
<p><span class="versionmodified">버전 3.5에 추가.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="SyntaxError">
<em class="property">exception </em><code class="descname">SyntaxError</code><a class="headerlink" href="#SyntaxError" title="정의 주소">¶</a></dt>
<dd><p>Raised when the parser encounters a syntax error.  This may occur in an
<a class="reference internal" href="../reference/simple_stmts.html#import"><code class="xref std std-keyword docutils literal"><span class="pre">import</span></code></a> statement, in a call to the built-in functions <a class="reference internal" href="functions.html#exec" title="exec"><code class="xref py py-func docutils literal"><span class="pre">exec()</span></code></a>
or <a class="reference internal" href="functions.html#eval" title="eval"><code class="xref py py-func docutils literal"><span class="pre">eval()</span></code></a>, or when reading the initial script or standard input
(also interactively).</p>
<p>Instances of this class have attributes <code class="xref py py-attr docutils literal"><span class="pre">filename</span></code>, <code class="xref py py-attr docutils literal"><span class="pre">lineno</span></code>,
<code class="xref py py-attr docutils literal"><span class="pre">offset</span></code> and <code class="xref py py-attr docutils literal"><span class="pre">text</span></code> for easier access to the details.  <a class="reference internal" href="stdtypes.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a>
of the exception instance returns only the message.</p>
</dd></dl>

<dl class="exception">
<dt id="IndentationError">
<em class="property">exception </em><code class="descname">IndentationError</code><a class="headerlink" href="#IndentationError" title="정의 주소">¶</a></dt>
<dd><p>Base class for syntax errors related to incorrect indentation.  This is a
subclass of <a class="reference internal" href="#SyntaxError" title="SyntaxError"><code class="xref py py-exc docutils literal"><span class="pre">SyntaxError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="TabError">
<em class="property">exception </em><code class="descname">TabError</code><a class="headerlink" href="#TabError" title="정의 주소">¶</a></dt>
<dd><p>Raised when indentation contains an inconsistent use of tabs and spaces.
This is a subclass of <a class="reference internal" href="#IndentationError" title="IndentationError"><code class="xref py py-exc docutils literal"><span class="pre">IndentationError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="SystemError">
<em class="property">exception </em><code class="descname">SystemError</code><a class="headerlink" href="#SystemError" title="정의 주소">¶</a></dt>
<dd><p>Raised when the interpreter finds an internal error, but the situation does not
look so serious to cause it to abandon all hope. The associated value is a
string indicating what went wrong (in low-level terms).</p>
<p>You should report this to the author or maintainer of your Python interpreter.
Be sure to report the version of the Python interpreter (<code class="docutils literal"><span class="pre">sys.version</span></code>; it is
also printed at the start of an interactive Python session), the exact error
message (the exception's associated value) and if possible the source of the
program that triggered the error.</p>
</dd></dl>

<dl class="exception">
<dt id="SystemExit">
<em class="property">exception </em><code class="descname">SystemExit</code><a class="headerlink" href="#SystemExit" title="정의 주소">¶</a></dt>
<dd><p>This exception is raised by the <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> function.  It inherits from
<a class="reference internal" href="#BaseException" title="BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> instead of <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> so that it is not accidentally
caught by code that catches <a class="reference internal" href="#Exception" title="Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a>.  This allows the exception to
properly propagate up and cause the interpreter to exit.  When it is not
handled, the Python interpreter exits; no stack traceback is printed.  The
constructor accepts the same optional argument passed to <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a>.
If the value is an integer, it specifies the system exit status (passed to
C's <code class="xref c c-func docutils literal"><span class="pre">exit()</span></code> function); if it is <code class="docutils literal"><span class="pre">None</span></code>, the exit status is zero; if
it has another type (such as a string), the object's value is printed and
the exit status is one.</p>
<p>A call to <a class="reference internal" href="sys.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> is translated into an exception so that clean-up
handlers (<a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal"><span class="pre">finally</span></code></a> clauses of <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal"><span class="pre">try</span></code></a> statements) can be
executed, and so that a debugger can execute a script without running the risk
of losing control.  The <a class="reference internal" href="os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal"><span class="pre">os._exit()</span></code></a> function can be used if it is
absolutely positively necessary to exit immediately (for example, in the child
process after a call to <a class="reference internal" href="os.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal"><span class="pre">os.fork()</span></code></a>).</p>
<dl class="attribute">
<dt id="SystemExit.code">
<code class="descname">code</code><a class="headerlink" href="#SystemExit.code" title="정의 주소">¶</a></dt>
<dd><p>The exit status or error message that is passed to the constructor.
(Defaults to <code class="docutils literal"><span class="pre">None</span></code>.)</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="TypeError">
<em class="property">exception </em><code class="descname">TypeError</code><a class="headerlink" href="#TypeError" title="정의 주소">¶</a></dt>
<dd><p>Raised when an operation or function is applied to an object of inappropriate
type.  The associated value is a string giving details about the type mismatch.</p>
<p>This exception may be raised by user code to indicate that an attempted
operation on an object is not supported, and is not meant to be. If an object
is meant to support a given operation but has not yet provided an
implementation, <a class="reference internal" href="#NotImplementedError" title="NotImplementedError"><code class="xref py py-exc docutils literal"><span class="pre">NotImplementedError</span></code></a> is the proper exception to raise.</p>
<p>Passing arguments of the wrong type (e.g. passing a <a class="reference internal" href="stdtypes.html#list" title="list"><code class="xref py py-class docutils literal"><span class="pre">list</span></code></a> when an
<a class="reference internal" href="functions.html#int" title="int"><code class="xref py py-class docutils literal"><span class="pre">int</span></code></a> is expected) should result in a <a class="reference internal" href="#TypeError" title="TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a>, but passing
arguments with the wrong value (e.g. a number outside expected boundaries)
should result in a <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal"><span class="pre">ValueError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnboundLocalError">
<em class="property">exception </em><code class="descname">UnboundLocalError</code><a class="headerlink" href="#UnboundLocalError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a reference is made to a local variable in a function or method, but
no value has been bound to that variable.  This is a subclass of
<a class="reference internal" href="#NameError" title="NameError"><code class="xref py py-exc docutils literal"><span class="pre">NameError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeError">
<em class="property">exception </em><code class="descname">UnicodeError</code><a class="headerlink" href="#UnicodeError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a Unicode-related encoding or decoding error occurs.  It is a
subclass of <a class="reference internal" href="#ValueError" title="ValueError"><code class="xref py py-exc docutils literal"><span class="pre">ValueError</span></code></a>.</p>
<p><a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> has attributes that describe the encoding or decoding
error.  For example, <code class="docutils literal"><span class="pre">err.object[err.start:err.end]</span></code> gives the particular
invalid input that the codec failed on.</p>
<dl class="attribute">
<dt id="UnicodeError.encoding">
<code class="descname">encoding</code><a class="headerlink" href="#UnicodeError.encoding" title="정의 주소">¶</a></dt>
<dd><p>The name of the encoding that raised the error.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.reason">
<code class="descname">reason</code><a class="headerlink" href="#UnicodeError.reason" title="정의 주소">¶</a></dt>
<dd><p>A string describing the specific codec error.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.object">
<code class="descname">object</code><a class="headerlink" href="#UnicodeError.object" title="정의 주소">¶</a></dt>
<dd><p>The object the codec was attempting to encode or decode.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.start">
<code class="descname">start</code><a class="headerlink" href="#UnicodeError.start" title="정의 주소">¶</a></dt>
<dd><p>The first index of invalid data in <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<dl class="attribute">
<dt id="UnicodeError.end">
<code class="descname">end</code><a class="headerlink" href="#UnicodeError.end" title="정의 주소">¶</a></dt>
<dd><p>The index after the last invalid data in <a class="reference internal" href="functions.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a>.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="UnicodeEncodeError">
<em class="property">exception </em><code class="descname">UnicodeEncodeError</code><a class="headerlink" href="#UnicodeEncodeError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during encoding.  It is a subclass of
<a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeDecodeError">
<em class="property">exception </em><code class="descname">UnicodeDecodeError</code><a class="headerlink" href="#UnicodeDecodeError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during decoding.  It is a subclass of
<a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeTranslateError">
<em class="property">exception </em><code class="descname">UnicodeTranslateError</code><a class="headerlink" href="#UnicodeTranslateError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during translating.  It is a subclass
of <a class="reference internal" href="#UnicodeError" title="UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ValueError">
<em class="property">exception </em><code class="descname">ValueError</code><a class="headerlink" href="#ValueError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a built-in operation or function receives an argument that has the
right type but an inappropriate value, and the situation is not described by a
more precise exception such as <a class="reference internal" href="#IndexError" title="IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ZeroDivisionError">
<em class="property">exception </em><code class="descname">ZeroDivisionError</code><a class="headerlink" href="#ZeroDivisionError" title="정의 주소">¶</a></dt>
<dd><p>Raised when the second argument of a division or modulo operation is zero.  The
associated value is a string indicating the type of the operands and the
operation.</p>
</dd></dl>

<p>The following exceptions are kept for compatibility with previous versions;
starting from Python 3.3, they are aliases of <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>.</p>
<dl class="exception">
<dt id="EnvironmentError">
<em class="property">exception </em><code class="descname">EnvironmentError</code><a class="headerlink" href="#EnvironmentError" title="정의 주소">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="IOError">
<em class="property">exception </em><code class="descname">IOError</code><a class="headerlink" href="#IOError" title="정의 주소">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="WindowsError">
<em class="property">exception </em><code class="descname">WindowsError</code><a class="headerlink" href="#WindowsError" title="정의 주소">¶</a></dt>
<dd><p>Only available on Windows.</p>
</dd></dl>

<div class="section" id="os-exceptions">
<h3>5.2.1. OS exceptions<a class="headerlink" href="#os-exceptions" title="제목 주소">¶</a></h3>
<p>The following exceptions are subclasses of <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>, they get raised
depending on the system error code.</p>
<dl class="exception">
<dt id="BlockingIOError">
<em class="property">exception </em><code class="descname">BlockingIOError</code><a class="headerlink" href="#BlockingIOError" title="정의 주소">¶</a></dt>
<dd><p>Raised when an operation would block on an object (e.g. socket) set
for non-blocking operation.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EAGAIN</span></code>, <code class="docutils literal"><span class="pre">EALREADY</span></code>,
<code class="docutils literal"><span class="pre">EWOULDBLOCK</span></code> and <code class="docutils literal"><span class="pre">EINPROGRESS</span></code>.</p>
<p>In addition to those of <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>, <a class="reference internal" href="#BlockingIOError" title="BlockingIOError"><code class="xref py py-exc docutils literal"><span class="pre">BlockingIOError</span></code></a> can have
one more attribute:</p>
<dl class="attribute">
<dt id="BlockingIOError.characters_written">
<code class="descname">characters_written</code><a class="headerlink" href="#BlockingIOError.characters_written" title="정의 주소">¶</a></dt>
<dd><p>An integer containing the number of characters written to the stream
before it blocked.  This attribute is available when using the
buffered I/O classes from the <a class="reference internal" href="io.html#module-io" title="io: Core tools for working with streams."><code class="xref py py-mod docutils literal"><span class="pre">io</span></code></a> module.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="ChildProcessError">
<em class="property">exception </em><code class="descname">ChildProcessError</code><a class="headerlink" href="#ChildProcessError" title="정의 주소">¶</a></dt>
<dd><p>Raised when an operation on a child process failed.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECHILD</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionError">
<em class="property">exception </em><code class="descname">ConnectionError</code><a class="headerlink" href="#ConnectionError" title="정의 주소">¶</a></dt>
<dd><p>A base class for connection-related issues.</p>
<p>Subclasses are <a class="reference internal" href="#BrokenPipeError" title="BrokenPipeError"><code class="xref py py-exc docutils literal"><span class="pre">BrokenPipeError</span></code></a>, <a class="reference internal" href="#ConnectionAbortedError" title="ConnectionAbortedError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionAbortedError</span></code></a>,
<a class="reference internal" href="#ConnectionRefusedError" title="ConnectionRefusedError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionRefusedError</span></code></a> and <a class="reference internal" href="#ConnectionResetError" title="ConnectionResetError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionResetError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="BrokenPipeError">
<em class="property">exception </em><code class="descname">BrokenPipeError</code><a class="headerlink" href="#BrokenPipeError" title="정의 주소">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a>, raised when trying to write on a
pipe while the other end has been closed, or trying to write on a socket
which has been shutdown for writing.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EPIPE</span></code> and <code class="docutils literal"><span class="pre">ESHUTDOWN</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionAbortedError">
<em class="property">exception </em><code class="descname">ConnectionAbortedError</code><a class="headerlink" href="#ConnectionAbortedError" title="정의 주소">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is aborted by the peer.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNABORTED</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionRefusedError">
<em class="property">exception </em><code class="descname">ConnectionRefusedError</code><a class="headerlink" href="#ConnectionRefusedError" title="정의 주소">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a>, raised when a connection attempt
is refused by the peer.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNREFUSED</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="ConnectionResetError">
<em class="property">exception </em><code class="descname">ConnectionResetError</code><a class="headerlink" href="#ConnectionResetError" title="정의 주소">¶</a></dt>
<dd><p>A subclass of <a class="reference internal" href="#ConnectionError" title="ConnectionError"><code class="xref py py-exc docutils literal"><span class="pre">ConnectionError</span></code></a>, raised when a connection is
reset by the peer.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ECONNRESET</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="FileExistsError">
<em class="property">exception </em><code class="descname">FileExistsError</code><a class="headerlink" href="#FileExistsError" title="정의 주소">¶</a></dt>
<dd><p>Raised when trying to create a file or directory which already exists.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EEXIST</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="FileNotFoundError">
<em class="property">exception </em><code class="descname">FileNotFoundError</code><a class="headerlink" href="#FileNotFoundError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a file or directory is requested but doesn't exist.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ENOENT</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="InterruptedError">
<em class="property">exception </em><code class="descname">InterruptedError</code><a class="headerlink" href="#InterruptedError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a system call is interrupted by an incoming signal.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <a class="reference internal" href="errno.html#errno.EINTR" title="errno.EINTR"><code class="xref py py-data docutils literal"><span class="pre">EINTR</span></code></a>.</p>
<div class="versionchanged">
<p><span class="versionmodified">버전 3.5으로 변경: </span>Python now retries system calls when a syscall is interrupted by a
signal, except if the signal handler raises an exception (see <span class="target" id="index-4"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0475"><strong>PEP 475</strong></a>
for the rationale), instead of raising <a class="reference internal" href="#InterruptedError" title="InterruptedError"><code class="xref py py-exc docutils literal"><span class="pre">InterruptedError</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="IsADirectoryError">
<em class="property">exception </em><code class="descname">IsADirectoryError</code><a class="headerlink" href="#IsADirectoryError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a file operation (such as <a class="reference internal" href="os.html#os.remove" title="os.remove"><code class="xref py py-func docutils literal"><span class="pre">os.remove()</span></code></a>) is requested
on a directory.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EISDIR</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="NotADirectoryError">
<em class="property">exception </em><code class="descname">NotADirectoryError</code><a class="headerlink" href="#NotADirectoryError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a directory operation (such as <a class="reference internal" href="os.html#os.listdir" title="os.listdir"><code class="xref py py-func docutils literal"><span class="pre">os.listdir()</span></code></a>) is requested
on something which is not a directory.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ENOTDIR</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="PermissionError">
<em class="property">exception </em><code class="descname">PermissionError</code><a class="headerlink" href="#PermissionError" title="정의 주소">¶</a></dt>
<dd><p>Raised when trying to run an operation without the adequate access
rights - for example filesystem permissions.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">EACCES</span></code> and <code class="docutils literal"><span class="pre">EPERM</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="ProcessLookupError">
<em class="property">exception </em><code class="descname">ProcessLookupError</code><a class="headerlink" href="#ProcessLookupError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a given process doesn't exist.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ESRCH</span></code>.</p>
</dd></dl>

<dl class="exception">
<dt id="TimeoutError">
<em class="property">exception </em><code class="descname">TimeoutError</code><a class="headerlink" href="#TimeoutError" title="정의 주소">¶</a></dt>
<dd><p>Raised when a system function timed out at the system level.
Corresponds to <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> <code class="docutils literal"><span class="pre">ETIMEDOUT</span></code>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified">버전 3.3에 추가: </span>All the above <a class="reference internal" href="#OSError" title="OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a> subclasses were added.</p>
</div>
<div class="admonition seealso">
<p class="first admonition-title">더 보기</p>
<p class="last"><span class="target" id="index-5"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3151"><strong>PEP 3151</strong></a> - Reworking the OS and IO exception hierarchy</p>
</div>
</div>
</div>
<div class="section" id="warnings">
<h2>5.3. Warnings<a class="headerlink" href="#warnings" title="제목 주소">¶</a></h2>
<p>The following exceptions are used as warning categories; see the <a class="reference internal" href="warnings.html#module-warnings" title="warnings: Issue warning messages and control their disposition."><code class="xref py py-mod docutils literal"><span class="pre">warnings</span></code></a>
module for more information.</p>
<dl class="exception">
<dt id="Warning">
<em class="property">exception </em><code class="descname">Warning</code><a class="headerlink" href="#Warning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warning categories.</p>
</dd></dl>

<dl class="exception">
<dt id="UserWarning">
<em class="property">exception </em><code class="descname">UserWarning</code><a class="headerlink" href="#UserWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings generated by user code.</p>
</dd></dl>

<dl class="exception">
<dt id="DeprecationWarning">
<em class="property">exception </em><code class="descname">DeprecationWarning</code><a class="headerlink" href="#DeprecationWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about deprecated features.</p>
</dd></dl>

<dl class="exception">
<dt id="PendingDeprecationWarning">
<em class="property">exception </em><code class="descname">PendingDeprecationWarning</code><a class="headerlink" href="#PendingDeprecationWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about features which will be deprecated in the future.</p>
</dd></dl>

<dl class="exception">
<dt id="SyntaxWarning">
<em class="property">exception </em><code class="descname">SyntaxWarning</code><a class="headerlink" href="#SyntaxWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about dubious syntax.</p>
</dd></dl>

<dl class="exception">
<dt id="RuntimeWarning">
<em class="property">exception </em><code class="descname">RuntimeWarning</code><a class="headerlink" href="#RuntimeWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about dubious runtime behavior.</p>
</dd></dl>

<dl class="exception">
<dt id="FutureWarning">
<em class="property">exception </em><code class="descname">FutureWarning</code><a class="headerlink" href="#FutureWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about constructs that will change semantically in the
future.</p>
</dd></dl>

<dl class="exception">
<dt id="ImportWarning">
<em class="property">exception </em><code class="descname">ImportWarning</code><a class="headerlink" href="#ImportWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings about probable mistakes in module imports.</p>
</dd></dl>

<dl class="exception">
<dt id="UnicodeWarning">
<em class="property">exception </em><code class="descname">UnicodeWarning</code><a class="headerlink" href="#UnicodeWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings related to Unicode.</p>
</dd></dl>

<dl class="exception">
<dt id="BytesWarning">
<em class="property">exception </em><code class="descname">BytesWarning</code><a class="headerlink" href="#BytesWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings related to <a class="reference internal" href="stdtypes.html#bytes" title="bytes"><code class="xref py py-class docutils literal"><span class="pre">bytes</span></code></a> and <a class="reference internal" href="stdtypes.html#bytearray" title="bytearray"><code class="xref py py-class docutils literal"><span class="pre">bytearray</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="ResourceWarning">
<em class="property">exception </em><code class="descname">ResourceWarning</code><a class="headerlink" href="#ResourceWarning" title="정의 주소">¶</a></dt>
<dd><p>Base class for warnings related to resource usage.</p>
<div class="versionadded">
<p><span class="versionmodified">버전 3.2에 추가.</span></p>
</div>
</dd></dl>

</div>
<div class="section" id="exception-hierarchy">
<h2>5.4. Exception hierarchy<a class="headerlink" href="#exception-hierarchy" title="제목 주소">¶</a></h2>
<p>The class hierarchy for built-in exceptions is:</p>
<div class="highlight-python3"><div class="highlight"><pre><span></span><span class="ne">BaseException</span>
 <span class="o">+--</span> <span class="ne">SystemExit</span>
 <span class="o">+--</span> <span class="ne">KeyboardInterrupt</span>
 <span class="o">+--</span> <span class="ne">GeneratorExit</span>
 <span class="o">+--</span> <span class="ne">Exception</span>
      <span class="o">+--</span> <span class="ne">StopIteration</span>
      <span class="o">+--</span> <span class="n">StopAsyncIteration</span>
      <span class="o">+--</span> <span class="ne">ArithmeticError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FloatingPointError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">OverflowError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ZeroDivisionError</span>
      <span class="o">+--</span> <span class="ne">AssertionError</span>
      <span class="o">+--</span> <span class="ne">AttributeError</span>
      <span class="o">+--</span> <span class="ne">BufferError</span>
      <span class="o">+--</span> <span class="ne">EOFError</span>
      <span class="o">+--</span> <span class="ne">ImportError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="n">ModuleNotFoundError</span>
      <span class="o">+--</span> <span class="ne">LookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndexError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">KeyError</span>
      <span class="o">+--</span> <span class="ne">MemoryError</span>
      <span class="o">+--</span> <span class="ne">NameError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnboundLocalError</span>
      <span class="o">+--</span> <span class="ne">OSError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BlockingIOError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ChildProcessError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">BrokenPipeError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionAbortedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionRefusedError</span>
      <span class="o">|</span>    <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ConnectionResetError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileExistsError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">FileNotFoundError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">InterruptedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IsADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotADirectoryError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">PermissionError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">ProcessLookupError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">TimeoutError</span>
      <span class="o">+--</span> <span class="ne">ReferenceError</span>
      <span class="o">+--</span> <span class="ne">RuntimeError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">NotImplementedError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="n">RecursionError</span>
      <span class="o">+--</span> <span class="ne">SyntaxError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">IndentationError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">TabError</span>
      <span class="o">+--</span> <span class="ne">SystemError</span>
      <span class="o">+--</span> <span class="ne">TypeError</span>
      <span class="o">+--</span> <span class="ne">ValueError</span>
      <span class="o">|</span>    <span class="o">+--</span> <span class="ne">UnicodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeDecodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeEncodeError</span>
      <span class="o">|</span>         <span class="o">+--</span> <span class="ne">UnicodeTranslateError</span>
      <span class="o">+--</span> <span class="ne">Warning</span>
           <span class="o">+--</span> <span class="ne">DeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">PendingDeprecationWarning</span>
           <span class="o">+--</span> <span class="ne">RuntimeWarning</span>
           <span class="o">+--</span> <span class="ne">SyntaxWarning</span>
           <span class="o">+--</span> <span class="ne">UserWarning</span>
           <span class="o">+--</span> <span class="ne">FutureWarning</span>
           <span class="o">+--</span> <span class="ne">ImportWarning</span>
           <span class="o">+--</span> <span class="ne">UnicodeWarning</span>
           <span class="o">+--</span> <span class="ne">BytesWarning</span>
           <span class="o">+--</span> <span class="ne">ResourceWarning</span>
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">목차</a></h3>
  <ul>
<li><a class="reference internal" href="#">5. 내장 예외</a><ul>
<li><a class="reference internal" href="#base-classes">5.1. 베이스 클래스</a></li>
<li><a class="reference internal" href="#concrete-exceptions">5.2. 구체적인 예외</a><ul>
<li><a class="reference internal" href="#os-exceptions">5.2.1. OS exceptions</a></li>
</ul>
</li>
<li><a class="reference internal" href="#warnings">5.3. Warnings</a></li>
<li><a class="reference internal" href="#exception-hierarchy">5.4. Exception hierarchy</a></li>
</ul>
</li>
</ul>

  <h4>이전 항목</h4>
  <p class="topless"><a href="stdtypes.html"
                        title="이전 장">4. 내장형</a></p>
  <h4>다음 항목</h4>
  <p class="topless"><a href="text.html"
                        title="다음 장">6. Text Processing Services</a></p>
  <div role="note" aria-label="source link">
    <h3>이 페이지</h3>
    <ul class="this-page-menu">
      <li><a href="../bugs.html">버그 보고하기</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/3.6/Doc/library/exceptions.rst"
            rel="nofollow">소스 보기
        </a>
      </li>
    </ul>
  </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>  
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>탐색</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="일반 색인"
             >색인</a></li>
        <li class="right" >
          <a href="../py-modindex.html" title="Python 모듈 목록"
             >모듈</a> |</li>
        <li class="right" >
          <a href="text.html" title="6. Text Processing Services"
             >다음</a> |</li>
        <li class="right" >
          <a href="stdtypes.html" title="4. 내장형"
             >이전</a> |</li>
        <li><img src="../_static/py.png" alt=""
                 style="vertical-align: middle; margin-top: -1px"/></li>
        <li><a href="https://www.python.org/">Python</a> &#187;</li>
        <li>
          <a href="../index.html">도큐멘테이션 </a> &#187;
        </li>

          <li class="nav-item nav-item-1"><a href="index.html" >파이썬 표준 라이브러리</a> &#187;</li>
    <li class="right">
        

    <div class="inline-search" style="display: none" role="search">
        <form class="inline-search" action="../search.html" method="get">
          <input placeholder="빠른 검색" type="text" name="q" />
          <input type="submit" value="Go" />
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
    <script type="text/javascript">$('.inline-search').show(0);</script>
         |
    </li>

      </ul>
    </div>  
    <div class="footer">
    &copy; <a href="../copyright.html">저작권</a> 2001-2018, Python Software Foundation.
    <br />
    한국어 번역 저작권 &copy; 2017-2018, Flowdas. All rights reserved.
    <br />
    <a href="http://sphinx.pocoo.org/">Sphinx</a> 1.6.5 를 사용해서 만들었습니다.
    </div>

  </body>
</html>